# Generated by Django 2.2.5 on 2021-03-10 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='カテゴリー名')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='企業名')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提出期限')),
            ],
        ),
        migrations.CreateModel(
            name='EntrySheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('content', models.TextField(blank=True, null=True, verbose_name='本文')),
                ('content_max_length', models.SmallIntegerField(blank=True, null=True, verbose_name='最大文字数')),
                ('content_min_length', models.SmallIntegerField(blank=True, null=True, verbose_name='最小文字数')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真3')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('categories', models.ManyToManyField(blank=True, null=True, to='es_manager.Category', verbose_name='カテゴリー')),
                ('companies', models.ManyToManyField(blank=True, null=True, to='es_manager.Company', verbose_name='企業')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
