# Generated by Django 2.2.5 on 2021-03-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('es_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrysheet',
            name='categories',
            field=models.ManyToManyField(blank=True, to='es_manager.Category', verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='entrysheet',
            name='companies',
            field=models.ManyToManyField(blank=True, to='es_manager.Company', verbose_name='企業'),
        ),
    ]
